In [ ]:
!pip install sagemaker==1.72.0

In [52]:
%matplotlib inline
import os
import ast
import json
import numpy as np
import pandas as pd
import source

import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
import sklearn.model_selection

import boto3
import sagemaker
from sagemaker import get_execution_role
from sagemaker.amazon.amazon_estimator import get_image_uri
from sagemaker.predictor import csv_serializer
from sagemaker.xgboost.estimator import XGBoost
from sagemaker.sklearn.estimator import SKLearn
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from IPython.display import Audio
sound_file = './sound/beep.wav'

import warnings
warnings.filterwarnings('ignore')

session = sagemaker.Session()
role = get_execution_role()

<h2> Data Processing </h2>

ROI is calculated using next price because we are trying to predict future ROI using the data from current time period.
Referred to https://github.com/NGYB/Stocks/blob/master/StockPricePrediction/StockPricePrediction_v1c_xgboost.ipynb

In [ ]:
DATA_DIR = './data'

In [4]:
data = pd.read_csv(os.path.join(DATA_DIR, 'crypto-historical-data.csv'), 
                   parse_dates=['time'], 
                   index_col=0, 
                   keep_default_na=False,
                   header=0,
                   names=['market_cap', 'name', 'price', 'sym', 'time', 'volume'])

data['rank'] = data.groupby("time")["market_cap"] \
                    .rank("dense", ascending=False) \
                    .astype(int)

data['market_share'] = data.groupby('time')["market_cap"] \
                    .apply(lambda x: x/float(x.sum()))

data['age'] = data.groupby(['sym'])["time"] \
                    .apply(lambda x: x - min(x)) \
                    .dt.days

next_price = data.groupby(['sym'])['price'].shift(-1)
data['roi'] = next_price/data['price'] - 1

In [5]:
data.head(10)

,market_cap,name,price,sym,time,volume,rank,market_share,age,roi
0,20461600.0,Viberate,0.114889,VIB,2018-04-01,4702470.0,250,0.000078,176,0.086658
1,19204400.0,Viberate,0.124845,VIB,2018-04-02,3688650.0,260,0.000076,177,0.069118
2,20825800.0,Viberate,0.133474,VIB,2018-04-03,3681530.0,253,0.000079,178,-0.087800
3,22260000.0,Viberate,0.121755,VIB,2018-04-04,5583970.0,250,0.000079,179,-0.028278
4,20086900.0,Viberate,0.118312,VIB,2018-04-05,2824800.0,251,0.000079,180,-0.016727
5,19692900.0,Viberate,0.116333,VIB,2018-04-06,2941990.0,257,0.000077,181,0.062665
6,19452600.0,Viberate,0.123623,VIB,2018-04-07,2648150.0,256,0.000078,182,0.027988
7,20606400.0,Viberate,0.127083,VIB,2018-04-08,4403120.0,257,0.000080,183,-0.015588
8,21145500.0,Viberate,0.125102,VIB,2018-04-09,4402010.0,257,0.000080,184,0.065403
9,21131200.0,Viberate,0.133284,VIB,2018-04-10,4475740.0,257,0.000082,185,0.081600

<h2> Data Selection </h2>

In [6]:
filtered = data.query('volume > 100000')

In [7]:
filtered.head()

,market_cap,name,price,sym,time,volume,rank,market_share,age,roi
0,20461600.0,Viberate,0.114889,VIB,2018-04-01,4702470.0,250,0.000078,176,0.086658
1,19204400.0,Viberate,0.124845,VIB,2018-04-02,3688650.0,260,0.000076,177,0.069118
2,20825800.0,Viberate,0.133474,VIB,2018-04-03,3681530.0,253,0.000079,178,-0.087800
3,22260000.0,Viberate,0.121755,VIB,2018-04-04,5583970.0,250,0.000079,179,-0.028278
4,20086900.0,Viberate,0.118312,VIB,2018-04-05,2824800.0,251,0.000079,180,-0.016727

<h2> Feature Engineering </h2>

In [27]:
feat = filtered.copy()

In [46]:
W = 3
TARGET = 'roi'

In [77]:
properties = ['market_cap', 'price', 'volume', 'rank', 'market_share', 'age', 'roi']
feat_columns = []

for p in properties:
    if p != TARGET:
        feat_columns.append(p)
        
        for w in range(1, W+1):
            col_name = "{}_lag_{}".format(p, w)
            feat[col_name] = feat.groupby(['sym'])[p].shift(w)
            feat_columns.append(col_name)
    
    feat[p + '_mean'] = feat[p].shift(1).rolling(w, min_periods=1).mean()
    feat[p + '_std'] = feat[p].shift(1).rolling(w, min_periods=1).std()
    print(p, len(feat.columns))

feat.dropna(inplace=True)

market_cap 42
price 42
volume 42
rank 42
market_share 42
age 42
roi 42

In [78]:
feat.head()

,market_cap,name,price,sym,time,volume,rank,market_share,age,roi,...,market_share_lag_3,market_share_mean,market_share_std,age_lag_1,age_lag_2,age_lag_3,age_mean,age_std,roi_mean,roi_std
12,19637600.0,Viberate,0.131197,VIB,2017-12-01,2562970.0,191,0.000066,55,0.020496,...,0.000082,0.000085,3.343084e-06,187.0,186.0,185.0,186.000000,1.000000,0.000192,0.124536
13,20889700.0,Viberate,0.133886,VIB,2017-12-02,1933420.0,193,0.000065,56,0.086768,...,0.000085,0.000080,1.237917e-05,55.0,187.0,186.0,142.666667,75.923207,-0.020176,0.108532
14,21623400.0,Viberate,0.145503,VIB,2017-12-03,3292750.0,193,0.000067,57,0.130685,...,0.000088,0.000073,1.337001e-05,56.0,55.0,187.0,99.333333,75.923207,-0.011969,0.118357
15,23451300.0,Viberate,0.164518,VIB,2017-12-04,4313180.0,186,0.000071,58,0.051873,...,0.000066,0.000066,9.092321e-07,57.0,56.0,55.0,56.000000,1.000000,0.079316,0.055471
16,26792700.0,Viberate,0.173052,VIB,2017-12-05,7439160.0,182,0.000078,59,-0.132041,...,0.000065,0.000068,2.866954e-06,58.0,57.0,56.0,57.000000,1.000000,0.089775,0.039492

<h2> Data Split </h2>

In [79]:
VAL_START = pd.Timestamp('2017-04-25')
TEST_START = pd.Timestamp('2017-10-25')

In [80]:
train = feat.query("time < @VAL_START")
val = feat.query("time >= @VAL_START & time <= @TEST_START")
trainval = feat.query("time <= @TEST_START")
test = feat.query("time >= @TEST_START")

In [81]:
cols_to_scale = feat_columns + [TARGET]

In [82]:
scaler_train = StandardScaler()
train_cols_scaled = scaler_train.fit_transform(train[cols_to_scale])
train_scaled = train.copy()
train_scaled[cols_to_scale] = train_cols_scaled

In [83]:
train_scaled.describe()

,market_cap,price,volume,rank,market_share,age,roi,market_cap_lag_1,market_cap_lag_2,market_cap_lag_3,...,market_share_lag_3,market_share_mean,market_share_std,age_lag_1,age_lag_2,age_lag_3,age_mean,age_std,roi_mean,roi_std
count,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,...,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,1.534900e+04,15349.000000,15349.000000,15349.000000,15349.000000
mean,-8.812129e-16,-4.691595e-16,5.577516e-16,2.427807e-15,-2.989841e-16,5.365728e-16,1.694448e-16,-5.028336e-17,2.843278e-16,1.599983e-16,...,7.387225e-16,7.054671e-02,2.406284e-02,1.952312e-16,3.163148e-16,6.568319e-16,819.667275,363.425303,5.287715,9.588665
std,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,1.000033e+00,...,1.000033e+00,1.998919e-01,6.049671e-02,1.000033e+00,1.000033e+00,1.000033e+00,338.466594,226.503117,15.794139,22.564645
min,-2.945563e-01,-2.811341e-01,-2.398116e-01,-6.821502e-01,-3.321423e-01,-1.426204e+00,-3.672089e-01,-2.226048e-01,-2.152955e-01,-1.976042e-01,...,-3.355329e-01,3.172660e-07,2.016534e-08,-1.720289e+00,-1.540420e+00,-1.816314e+00,1.000000,1.000000,-0.999994,0.000000
25%,-2.908312e-01,-2.810321e-01,-2.370712e-01,-5.619743e-01,-3.293778e-01,-9.160326e-01,-3.480693e-01,-2.215390e-01,-2.147139e-01,-1.967107e-01,...,-3.328704e-01,8.110201e-04,2.419117e-04,-8.278275e-01,-8.922167e-01,-8.256658e-01,551.666667,210.444767,-0.191408,0.473801
50%,-2.835729e-01,-2.781291e-01,-2.289777e-01,-3.616812e-01,-3.215536e-01,-1.190487e-01,-3.041624e-01,-2.157839e-01,-2.130941e-01,-1.916125e-01,...,-3.239079e-01,2.711993e-03,1.540087e-03,-9.613289e-02,-1.937021e-03,-1.146333e-02,860.000000,365.000000,1.108811,2.657710
75%,-2.364200e-01,-2.565055e-01,-1.856525e-01,1.190223e-01,-2.734137e-01,8.479923e-01,-4.191462e-02,-1.798675e-01,-1.986475e-01,-1.681686e-01,...,-2.614209e-01,2.042991e-02,7.776341e-03,8.581618e-01,8.223219e-01,8.112425e-01,1088.666667,557.546710,5.477742,10.112504
max,8.614784e+00,1.276354e+01,2.269790e+01,1.421966e+01,3.802569e+00,2.271903e+00,2.568387e+01,1.463427e+01,1.464107e+01,1.548290e+01,...,4.175610e+00,8.755433e-01,3.237200e-01,2.010323e+00,2.080717e+00,2.031483e+00,1782.000000,860.740573,716.927901,530.450552

<h2> Data Scaling </h2>

In [84]:
scaler_trainval = StandardScaler()
trainval_cols_scaled = scaler_trainval.fit_transform(trainval[cols_to_scale])
trainval_scaled = trainval.copy()
trainval_scaled[cols_to_scale] = trainval_cols_scaled

In [104]:
def scale_col(df, base, col):
    mean = df[base+'_mean']
    std = df[base+'_std']
    std = np.where(std == 0, 0.001, std)
    return (df[col] - mean)/std

In [107]:
val_scaled = val.copy()
for p in properties:
    val_scaled[p] = scale_col(val_scaled, p, p)
    
    if p != TARGET:
        for w in range(1, W+1):
            col_name = "{}_lag_{}".format(p, w)
            val_scaled[col_name] = scale_col(val_scaled, p, col_name)

In [109]:
test_scaled = test.copy()
for p in properties:
    test_scaled[p] = scale_col(test_scaled, p, p)
    
    if p != TARGET:
        for w in range(1, W+1):
            col_name = "{}_lag_{}".format(p, w)
            test_scaled[col_name] = scale_col(test_scaled, p, col_name)

In [110]:
test_scaled.describe()

,market_cap,price,volume,rank,market_share,age,roi,market_cap_lag_1,market_cap_lag_2,market_cap_lag_3,...,market_share_lag_3,market_share_mean,market_share_std,age_lag_1,age_lag_2,age_lag_3,age_mean,age_std,roi_mean,roi_std
count,53362.000000,53362.000000,5.336200e+04,5.336200e+04,53362.000000,53362.000000,53362.000000,53362.000000,53362.000000,53362.000000,...,53362.000000,5.336200e+04,5.336200e+04,53362.000000,53362.000000,53362.000000,53362.000000,53362.000000,53362.000000,53362.000000
mean,3.245548,2.875137,-6.139197e+02,1.320924e+03,0.246209,2.646620,5.715785,-0.036055,0.034318,0.001737,...,0.116395,3.988125e-03,6.738116e-04,0.814818,0.035904,-0.850723,427.203428,40.268228,2.569417,2.299949
std,89.556781,66.715254,1.452820e+05,1.155905e+05,19.801757,26.763291,449.218315,0.851155,0.725022,0.863844,...,0.856494,4.825420e-02,5.508658e-03,0.517288,0.354627,0.466603,456.354837,120.356021,34.373764,15.201654
min,-355.026898,-640.000000,-3.356033e+07,-8.704578e+05,-438.743570,-149.000010,-275.900714,-1.154701,-1.154700,-1.154701,...,-1.154701,9.672461e-08,4.946122e-09,-1.154700,-1.154700,-1.154700,1.000000,1.000000,-0.999993,0.000000
25%,-1.111662,-1.194636,-9.480582e-01,-5.913398e-01,-1.310811,2.000000,-1.085014,-0.871890,-0.578623,-0.852553,...,-0.744055,4.850539e-05,2.444393e-06,1.000000,0.000000,-1.000000,86.000000,1.000000,-0.643318,0.016159
50%,0.184176,0.055623,-2.139113e-01,5.773503e-01,-0.372537,2.000000,-0.276396,-0.166162,0.008778,-0.073247,...,0.317694,1.290995e-04,7.755005e-06,1.000000,0.000000,-1.000000,205.000000,1.000000,-0.024742,0.073705
75%,1.253692,1.210502,1.171766e+00,1.456986e+00,0.923810,2.000000,0.809293,0.865720,0.663962,0.918409,...,0.981662,4.173574e-04,3.203377e-05,1.000000,0.000000,-1.000000,699.583333,1.000000,0.043912,0.167536
max,13829.715713,10403.841667,4.904785e+04,1.801713e+07,3383.524787,1463.000088,59658.708485,1.154701,1.154701,1.154705,...,1.154701,8.925229e-01,1.365649e-01,1.154700,1.154700,1.154700,1790.000000,875.555252,2023.532953,896.258199

In [111]:
test_scaled.head()

,market_cap,name,price,sym,time,volume,rank,market_share,age,roi,...,market_share_lag_3,market_share_mean,market_share_std,age_lag_1,age_lag_2,age_lag_3,age_mean,age_std,roi_mean,roi_std
12,-1.904294,Viberate,-1.240722,VIB,2017-12-01,-1.427527,-15.500000,-5.854664,-131.000000,0.163035,...,-1.001655,0.000085,3.343084e-06,1.000000,0.000000,-1.000000,186.000000,1.000000,0.000192,0.124536
13,-0.514127,Viberate,-0.811061,VIB,2017-12-02,-1.114489,-1.095142,-1.183577,-1.141504,0.985361,...,0.437760,0.000080,1.237917e-05,-1.154675,0.583923,0.570752,142.666667,75.923207,-0.020176,0.108532
14,0.021833,Viberate,0.510388,VIB,2017-12-03,1.403376,-0.546711,-0.463770,-0.557581,1.205284,...,1.154509,0.000073,1.337001e-05,-0.570752,-0.583923,1.154675,99.333333,75.923207,-0.011969,0.118357
15,2.723196,Viberate,3.637441,VIB,2017-12-04,2.523665,-5.484828,5.341740,2.000000,-0.494733,...,-0.288405,0.000066,9.092321e-07,1.000000,0.000000,-1.000000,56.000000,1.000000,0.079316,0.055471
16,3.642101,Viberate,1.622007,VIB,2017-12-05,3.567631,-2.144444,3.500104,2.000000,-5.616756,...,-0.856544,0.000068,2.866954e-06,1.000000,0.000000,-1.000000,57.000000,1.000000,0.089775,0.039492

In [112]:
train_X = train_scaled[feat_columns]
train_Y = train_scaled[[TARGET]]

trainval_X = trainval_scaled[feat_columns]
trainval_Y = trainval_scaled[[TARGET]]

val_X = val_scaled[feat_columns]
val_Y = val_scaled[[TARGET]]

test_X = test_scaled[feat_columns]
test_Y = test_scaled[[TARGET]]

<h2> Training </h2>

In [ ]:
prefix = 'xgboost-new'

pd.concat([train_Y, train_X], axis=1).to_csv(os.path.join(data_dir, 'train.csv'), header=False, index=False)
pd.concat([val_Y, val_X], axis=1).to_csv(os.path.join(data_dir, 'val.csv'), header=False, index=False)

train_location = session.upload_data(os.path.join(data_dir, 'train.csv'), key_prefix=prefix)
val_location = session.upload_data(os.path.join(data_dir, 'val.csv'), key_prefix=prefix)

s3_input_train = sagemaker.s3_input(s3_data=train_location, content_type='text/csv')
s3_input_validation = sagemaker.s3_input(s3_data=val_location, content_type='text/csv')

In [ ]:
container = get_image_uri(session.boto_region_name, 'xgboost')